Am folosit lifting up the state pentru charturi
cezarmocanu/weatherly-com pull request #3
Opened 2023-10-05 14:33 UTC by malexa21

Am modificat exportul pentru datele celor doua charturi astfel incat sa aiba mereu locatia comuna. De asemenea a ramas doar un buton de "Change Location" care schimba simultan orasele pentru ambele charturi de la asia de est. Mai am de modificat pozitia acestora. Momentan aceasta este solutia pe care am gasit-o, revin mai tarziu cu o modificare.

2023-10-06 17:09 UTC, RazvanMocanu1 approved these changes

2023-10-06 17:11 UTC, costiy approved these changes

2023-10-07 09:56 UTC, cezarmocanu requested changes

2023-10-07 09:56 UTC, cezarmocanu commented on src/components/asia-tab/AsiaTab.jsx
> +          <div className="weather-tab">
Te rog aliniază codul astfel încât sa îmi pot da seama care element este în care

Greu de citit
```
<div>
      <div>
           <A/>
      <B/>
 </div>
</div>
```

Usor de citit
```
<div>
      <div>
           <A/>
           <B/>
      </div>
</div>
```

2023-10-07 09:56 UTC, cezarmocanu commented on src/components/asia-humidity-chart/AsiaHumidityChart.jsx
> +    <div className="chart">
Tine cont de aliniere

2023-10-07 15:35 UTC, cezarmocanu approved these changes

2023-10-10 06:43 UTC, merged