Am mutat state-ul comun in componenta parinte. Am sters butoanele ind…
cezarmocanu/weatherly-com pull request #4
Opened 2023-10-05 21:05 UTC by AndreeaMereu

…ividuale de la cele doua chart-uri si am creat un singur buton care afiseaza aceeasi locatie la ambele chart-uri.

2023-10-06 13:26 UTC, malexa21 approved these changes

2023-10-06 13:35 UTC, RazvanMocanu1 approved these changes

2023-10-07 09:53 UTC, cezarmocanu requested changes

2023-10-07 09:53 UTC, cezarmocanu commented on src/components/europe-weather-tab/EuropeWeatherTab.jsx
> +      <button onClick={handleChangeLocationClick}>Change Location</button>
Poziția butonului nu arata cum arata înainte. Butonul ar trebui sa rămână în stânga jos, nu sa fie cât charturile de mare

2023-10-10 18:36 UTC, malexa21 approved these changes

2023-10-10 18:44 UTC, merged